### ISSUE TITLE
error: Could not compile `libflate`.

### ISSUE THREAD

**Issue by iwconfig** [bobbo/spotify-connect-scrobbler#8]
Seems like a bug, but I'm not in any way familiar with Rust. I have no idea how to solve this.

       Compiling libflate v0.1.11
    error: `pub(restricted)` syntax is experimental (see issue #32409)
       --> /home/d/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.11/src/zlib.rs:202:9
        |
    202 |     pub(crate) fn read_from<R>(mut reader: R) -> io::Result<Self>
        |         ^^^^^

    error: `pub(restricted)` syntax is experimental (see issue #32409)
      --> /home/d/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.11/src/gzip.rs:98:5
       |
    98 | pub(crate) struct Trailer {
       |     ^^^^^

    error: `pub(restricted)` syntax is experimental (see issue #32409)
       --> /home/d/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.11/src/gzip.rs:370:9
        |
    370 |     pub(crate) fn read_from<R>(mut reader: R) -> io::Result<Self>
        |         ^^^^^

    error: `pub(restricted)` syntax is experimental (see issue #32409)
      --> /home/d/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.11/src/deflate/mod.rs:29:5
       |
    29 | pub(crate) mod symbol;
       |     ^^^^^

    error: `pub(restricted)` syntax is experimental (see issue #32409)
      --> /home/d/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.11/src/non_blocking/deflate/decode.rs:72:9
       |
    72 |     pub(crate) fn bit_reader_mut(&mut self) -> &mut TransactionalBitReader<R> {
       |         ^^^^^

    error: `pub(restricted)` syntax is experimental (see issue #32409)
       --> /home/d/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.11/src/bit.rs:143:9
        |
    143 |     pub(crate) fn state(&self) -> BitReaderState {
        |         ^^^^^

    error: `pub(restricted)` syntax is experimental (see issue #32409)
       --> /home/d/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.11/src/bit.rs:150:9
        |
    150 |     pub(crate) fn restore_state(&mut self, state: BitReaderState) {
        |         ^^^^^

    error: `pub(restricted)` syntax is experimental (see issue #32409)
       --> /home/d/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.11/src/bit.rs:171:5
        |
    171 | pub(crate) struct BitReaderState {
        |     ^^^^^

    error: aborting due to 8 previous errors

    error: Could not compile `libflate`.
    Build failed, waiting for other jobs to finish...
    error: build failed

**Comment by dmfutcher** [comment]
Which version of Rust are you using? I can't reproduce this with the latest `rustc` stable (1.21). The error points to rust-lang/rust#32409, which I believe stabilized in 1.18. 

I should add a note to the README that Rust 1.18 is the minimum required version.

**Comment by iwconfig** [comment]
Oh, yes that struck my mind when i woke up this morning. I installed the latest from the Ubuntu repository.

    · rustc --version
    rustc 1.17.0

Of course I should have checked the version since its almost always out of date. It works now. Oh well! 

By the way, I also had to install a [dev package regarding openssl-sys.](https://github.com/sfackler/rust-openssl/issues/649) Maybe you should add a note about that also.

Many thanks! :)
