### ISSUE TITLE
Pipe audio data to /dev/null

### ISSUE THREAD

**Issue by iwconfig** [bobbo/spotify-connect-scrobbler#9]
This is a minor issue but when I connect my Spotify client to the Scrobbler, i.e. set s-c-s as the audio source, I get the audio data output in my terminal.

I also noticed when building s-c-s, it compiled ogg and vorbis packages. Is these even necessary? Or are they up for removal in the *remove-audio-backends* branch?

**Comment by dmfutcher** [comment]
Yes, absolutely plan to remove the audio backends & audio playback features that were pulled in from `librespot`, have raised this as #11.  Piping the data to /dev/null as a temporary stop-gap can be implemented.

**Comment by dmfutcher** [comment]
This is closed and "released" (for all that means at the moment) in v0.1.2. Note: tracks "played" through the Scrobbler will not be scrobbled. But at least this stops it breaking your terminal if Scrobbler is selected in the Connect menu.
